# Dependencies
highligher:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            'sheerun'
tagline:          'homepage'
description:      'Adam Stankiewicz'
url:              http://getpoole.com

author:
  name:           'Adam Stankiewicz'
  url:            https://twitter.com/sheerun

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sheerun/blog

gravatar:
  size: 215
  secure: true

theme: jekyll-theme-tactile
